-- Roles Data
INSERT INTO MyFirstDatabase.dbo.Roles (Name) VALUES (N'AWPer');
INSERT INTO MyFirstDatabase.dbo.Roles (Name) VALUES (N'In-game Leader');
INSERT INTO MyFirstDatabase.dbo.Roles (Name) VALUES (N'Rifler');

-- Teams Data
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'FaZe', 1);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Vitality', 2);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'MOUZ', 3);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'ENCE', 4);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Complexity', 5);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'G2', 6);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Monte', 7);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Natus Vincere', 8);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Cloud9', 9);
INSERT INTO MyFirstDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Virtus.pro', 10);

-- Players Data
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'karrigan', N'Finn', N'Andersen');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'rain', N'Håvard', N'Nygaard');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Twistzz', N'Russel', N'Van Dulken');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'ropz', N'Robin', N'Kool');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'broky', N'Helvijs', N'Saukants');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'apEX', N'Dan', N'Madesclaire');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'ZywOo', N'Mathieu', N'Herbaut');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'flameZ', N'Shahar', N'Shushan');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Spinx', N'Lotan', N'Giladi');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'mezii', N'William', N'Merriman');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'frozen', N'David', N'Cernanský');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'siuhy', N'Kamil', N'Szkaradek');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'torzsi', N'Ádám', N'Torzsás');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Jimpphat', N'Jimi', N'Salo');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'xertioN', N'Dorian', N'Berman');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'gla1ve', N'Lukas', N'Rossander');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'NertZ', N'Guy', N'Iluz');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Maden', N'Pavle', N'Boškovic');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'dycha', N'Pawel', N'Dycha');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'SunPayus', N'Alvaro', N'Garcia');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'EliGE', N'Jonathan', N'Jablonowski');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'JT', N'Johnny', N'Theodosiou');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'floppy', N'Ricky', N'Kemery');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'hallzerk', N'Håkon', N'Fjærli');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Grim', N'Michael', N'Wince');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'NiKo', N'Nikola', N'Kovac');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'huNter-', N'Nemanja', N'Kovac');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'nexa', N'Nemanja', N'Isakovic');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'HooXi', N'Rasmus', N'Nielsen');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'm0NESY', N'Ilya', N'Osipov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'sdy', N'Viktor', N'Orudzhev');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'br0', N'Alexander', N'Bro');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Woro2k', N'Volodymyr', N'Veletniuk');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'DemQQ', N'Sergiy', N'Demchenko');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'kRaSnaL', N'Szymon', N'Mrozek');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Aleksib', N'Aleksi', N'Virolainen');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'iM', N'Mihai', N'Ivan');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'b1t', N'Valeriy', N'Vakhovskiy');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'jL', N'Justinas', N'Lekavicius');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'w0nderful', N'Ihor', N'Zhdanov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'HObbit', N'Abay', N'Khassenov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'electroNic', N'Denis', N'Sharipov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Boombl4', N'Kirill', N'Mikhailov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Ax1Le', N'Sergey', N'Rykhtorov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Perfecto', N'Ilya', N'Zalutskiy');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'mir', N'Nikolay', N'Bityukov');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'FL1T', N'Evgenii', N'Lebedev');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'Jame', N'Dzhami', N'Ali');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'n0rb3r7', N'David', N'Danielyan');
INSERT INTO MyFirstDatabase.dbo.Players (Alias, FirstName, LastName) VALUES (N'fame', N'Petr', N'Bolyshev');

-- PlayerContracts Data
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (2, 1, 1);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (5, 2, 1);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (3, 1, 1);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (1, 3, 1);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (4, 1, 1);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (6, 3, 3);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (7, 2, 3);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (9, 1, 3);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (8, 1, 3);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (10, 1, 3);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (11, 1, 4);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (13, 2, 4);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (15, 1, 4);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (12, 3, 4);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (14, 1, 4);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (19, 1, 5);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (18, 1, 5);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (20, 2, 5);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (17, 1, 5);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (16, 3, 5);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (22, 3, 6);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (23, 1, 6);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (25, 1, 6);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (24, 2, 6);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (21, 1, 6);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (27, 1, 7);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (26, 1, 7);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (30, 2, 7);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (29, 3, 7);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (28, 3, 7);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (33, 2, 8);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (34, 1, 8);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (35, 1, 8);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (31, 3, 8);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (32, 1, 8);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (38, 1, 9);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (36, 3, 9);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (39, 1, 9);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (37, 1, 9);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (40, 1, 9);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (44, 1, 10);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (41, 1, 10);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (42, 1, 10);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (45, 1, 10);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (43, 3, 10);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (48, 3, 11);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (47, 1, 11);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (50, 1, 11);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (49, 1, 11);
INSERT INTO MyFirstDatabase.dbo.PlayerContracts (PlayerId, RoleId, TeamId) VALUES (46, 1, 11);
