INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'FaZe Clan', 1);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'MOUZ', 2);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'ENCE', 3);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'G2', 4);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Vitality', 5);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Complexity', 6);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Monte', 7);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Natus Vincere', 8);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Astralis', 9);
INSERT INTO TestDatabase.dbo.Teams (Name, WorldRanking) VALUES (N'Virtus.pro', 10);
